{{-- Post Sidebar Component --}}
<aside class="space-y-8">
    <!-- Table of Contents -->
    @if($post->content)
    <div class="blog-sidebar">
        <h3 class="text-lg font-bold text-gray-900 dark:text-gray-100 mb-4">Table of Contents</h3>
        <div id="table-of-contents" class="text-sm">
            <!-- TOC will be generated by JavaScript -->
        </div>
    </div>
    @endif

    <!-- Post Info -->
    <div class="blog-sidebar">
        <h3 class="text-lg font-bold text-gray-900 dark:text-gray-100 mb-4">Post Information</h3>
        <dl class="space-y-3 text-sm">
            <div>
                <dt class="text-gray-500 dark:text-gray-400">Published</dt>
                <dd class="text-gray-900 dark:text-gray-100">
                    {{ $post->published_at->format('F j, Y') }}
                </dd>
            </div>
            
            <div>
                <dt class="text-gray-500 dark:text-gray-400">Author</dt>
                <dd class="text-gray-900 dark:text-gray-100">
                    {{ $post->user->name }}
                </dd>
            </div>

            @if($post->reading_time)
            <div>
                <dt class="text-gray-500 dark:text-gray-400">Reading Time</dt>
                <dd class="text-gray-900 dark:text-gray-100">
                    {{ $post->reading_time }} minutes
                </dd>
            </div>
            @endif

            @if(config('blog.features.view_counts'))
            <div>
                <dt class="text-gray-500 dark:text-gray-400">Views</dt>
                <dd class="text-gray-900 dark:text-gray-100">
                    {{ number_format($post->view_count) }}
                </dd>
            </div>
            @endif

            @if($post->updated_at->gt($post->published_at))
            <div>
                <dt class="text-gray-500 dark:text-gray-400">Last Updated</dt>
                <dd class="text-gray-900 dark:text-gray-100">
                    {{ $post->updated_at->format('F j, Y') }}
                </dd>
            </div>
            @endif
        </dl>
    </div>

    <!-- Categories Widget -->
    @if($categories && $categories->count() > 0)
    <div class="blog-sidebar">
        <h3 class="text-lg font-bold text-gray-900 dark:text-gray-100 mb-4">Categories</h3>
        <ul class="space-y-2">
            @foreach($categories as $category)
            <li>
                <a href="{{ route('blog.categories.show', $category->slug) }}" 
                   class="flex items-center justify-between text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors py-2">
                    <span class="flex items-center">
                        <div class="w-3 h-3 rounded-full mr-3" 
                             style="background-color: {{ $category->color }}"></div>
                        {{ $category->name }}
                    </span>
                    <span class="text-sm text-gray-500 dark:text-gray-500">
                        {{ $category->posts_count }}
                    </span>
                </a>
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <!-- Popular Tags Widget -->
    @if($popularTags && $popularTags->count() > 0)
    <div class="blog-sidebar">
        <h3 class="text-lg font-bold text-gray-900 dark:text-gray-100 mb-4">Popular Tags</h3>
        <div class="flex flex-wrap gap-2">
            @foreach($popularTags as $tag)
                <a href="{{ route('blog.tags.show', $tag->slug) }}" 
                   class="blog-tag"
                   style="{{ $tag->css_color }}">
                    #{{ $tag->name }}
                    <span class="ml-1 text-xs opacity-75">({{ $tag->usage_count }})</span>
                </a>
            @endforeach
        </div>
    </div>
    @endif

    <!-- Recent Posts Widget -->
    @if($recentPosts && $recentPosts->count() > 0)
    <div class="blog-sidebar">
        <h3 class="text-lg font-bold text-gray-900 dark:text-gray-100 mb-4">Recent Posts</h3>
        <div class="space-y-4">
            @foreach($recentPosts as $recentPost)
            <article class="group">
                <div class="flex space-x-3">
                    @if($recentPost->featured_image)
                    <div class="flex-shrink-0">
                        <a href="{{ $recentPost->url }}">
                            <img src="{{ asset('storage/' . $recentPost->featured_image) }}" 
                                 alt="{{ $recentPost->featured_image_alt ?: $recentPost->title }}"
                                 class="w-16 h-16 object-cover rounded-lg group-hover:opacity-90 transition-opacity">
                        </a>
                    </div>
                    @endif

                    <div class="flex-1 min-w-0">
                        <h4 class="text-sm font-medium text-gray-900 dark:text-gray-100 group-hover:text-gray-600 dark:group-hover:text-gray-300 transition-colors line-clamp-2">
                            <a href="{{ $recentPost->url }}">
                                {{ $recentPost->title }}
                            </a>
                        </h4>
                        
                        <div class="mt-2 flex items-center text-xs text-gray-500 dark:text-gray-400">
                            <time datetime="{{ $recentPost->published_at->toISOString() }}">
                                {{ $recentPost->published_at->format('M j, Y') }}
                            </time>
                            @if($recentPost->reading_time)
                                <span class="mx-1">•</span>
                                <span>{{ $recentPost->reading_time }} min</span>
                            @endif
                        </div>
                    </div>
                </div>
            </article>
            @endforeach
        </div>
    </div>
    @endif

    <!-- Share Widget -->
    <div class="blog-sidebar">
        <h3 class="text-lg font-bold text-gray-900 dark:text-gray-100 mb-4">Share This Post</h3>
        <div class="flex space-x-3">
            <button onclick="shareBlogPost('{{ $post->url }}', '{{ addslashes($post->title) }}', 'twitter')"
                    class="p-2 text-gray-500 hover:text-blue-500 transition-colors">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>
                </svg>
            </button>
            <button onclick="shareBlogPost('{{ $post->url }}', '{{ addslashes($post->title) }}', 'facebook')"
                    class="p-2 text-gray-500 hover:text-blue-600 transition-colors">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                </svg>
            </button>
            <button onclick="shareBlogPost('{{ $post->url }}', '{{ addslashes($post->title) }}', 'linkedin')"
                    class="p-2 text-gray-500 hover:text-blue-700 transition-colors">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                </svg>
            </button>
            <button onclick="copyBlogLink('{{ $post->url }}')"
                    class="p-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 transition-colors">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path>
                </svg>
            </button>
        </div>
    </div>
</aside>